name: CI
on:
  push: 
  workflow_dispatch:
jobs:
  # Reusable zig env:
  zig:
    uses: ./.github/workflows/zig.yml  # <--- (1) zig uses job is required
  # Testing jobs:
  zig-01-hello:
    needs: zig                         # <--- (2) needs of job zig is required
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4         # <--- (3) same cache config is required
        with:
          path: |
            ~/.zig
            ~/.local
            ~/.cache/zig
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml') }}
      - run: zig version
      - run: cd zig-01-hello ; zig build --summary all
      - run: cd zig-01-hello ; ./zig-out/bin/hello
