name: zig
on:
  # Allows you to reuse local workflow from other repository GitHub Actions
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      ZIG_BIN:
        description: "zig bin directory"
        value: ${{ jobs.zig.outputs.ZIG_BIN }}
jobs:
  zig:
    name: zig
    runs-on: ubuntu-latest
    # declare zig job outputs
    outputs:
      ZIG_BIN: ${{ steps.bin.outputs.ZIG_BIN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        id: zig-cache
        with:
          path: |
            ~/.zig
            ~/.local
            ~/.cache/zig
          key: ${{ hashFiles('**/workflows/*.yml') }}
      - run: |
          PATH="$HOME/.local/zig:$PATH" command -v zig >/dev/null 2>&1 || {
            echo >&2 "Zig is required but not installed."                                     ;
            echo >&2 "sudo apt install -yqq curl tar xz-utils"                                ;
            sudo apt install -yqq curl tar xz-utils                                           ;
            if [[ "$OSTYPE" == "linux-gnu"* ]] && [[ "$(uname -m)" == "arm64" ]] ; then
              export ZIG_DISTRIBUTION="zig-linux-aarch64-0.14.0-dev.2851+b074fb7dd"           ;
              echo >&2 "export ZIG_DISTRIBUTION=$ZIG_DISTRIBUTION"                            ;
            elif [[ "$OSTYPE" == "linux-gnu"* ]] ; then
              export ZIG_DISTRIBUTION="zig-linux-x86_64-0.14.0-dev.2851+b074fb7dd"            ;
              echo >&2 "export ZIG_DISTRIBUTION=$ZIG_DISTRIBUTION"                            ;
            elif [[ "$OSTYPE" == "darwin"* ]] && [[ "$(uname -m)" == "arm64" ]] ; then
              export ZIG_DISTRIBUTION="zig-macos-aarch64-0.14.0-dev.2851+b074fb7dd"           ;
              echo >&2 "export ZIG_DISTRIBUTION=$ZIG_DISTRIBUTION"                            ;
            elif [[ "$OSTYPE" == "darwin"* ]] ; then
              export ZIG_DISTRIBUTION="zig-macos-x86_64-0.14.0-dev.2851+b074fb7dd"            ;
              echo >&2 "export ZIG_DISTRIBUTION=$ZIG_DISTRIBUTION"                            ;
            fi                                                                                ;
            export ZIG_URL="https://ziglang.org/builds/${ZIG_DISTRIBUTION}.tar.xz"            ;
            echo >&2 "ZIG_URL=${ZIG_URL}"                                                     ;
            export ZIG_HOME="$HOME/.local/zig"                                                ;
            echo >&2 "export ZIG_HOME=${ZIG_HOME}"                                            ;
            echo >&2 "mkdir -pv ~/.local/bin ${ZIG_HOME}"                                     ;
            # test ! -d ~/.local/zig || mv -fv ~/.local/zig ~/.local/zig-$(date +%Y-%m-%d-%H-%M-%S) ;
            mkdir -pv ~/.local/bin "${ZIG_HOME}"                                              ;
            echo >&2 "curl -LSs ${ZIG_URL} | tar -xJ -C "${ZIG_HOME}" --strip-components=1"   ;
            curl -LSs ${ZIG_URL} | tar -xJ -C "${ZIG_HOME}" --strip-components=1              ;
            echo >&2 "ln -sv ${ZIG_HOME}/zig ~/.local/bin/zig"                                ;
            ln -sv "${ZIG_HOME}/zig" ~/.local/bin/zig                                         ; 
            export ZIG_VERSION=`${ZIG_HOME}/zig version`               ;
            echo >&2 "export ZIG_VERSION=${ZIG_VERSION}"                                      ;
            echo "Installed ${ZIG_VERSION} version of zig."                                   ;
          }
          ${HOME}/.local/zig/zig env
      # set zig job outputs
      - id: bin
        run: echo "ZIG_BIN=${HOME}/.local/zig" >> $GITHUB_OUTPUT
#Usage:
#name: ...
#on: [...]
#jobs:
#  zig:
#    uses: ./.github/workflows/zig.yml  # <--- (1) zig uses job is required
#  job1:
#    runs-on: ubuntu-latest
#    needs: zig                         # <--- (2) needs of job zig is required
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/cache@v4         # <--- (3) same cache config is required
#        with:
#          path: |
#            ~/.zig
#            ~/.local
#            ~/.cache/zig
#          key: ${{ hashFiles('**/workflows/*.yml') }}
#      - run: zig version
