name: zig
on:
  # Allows you to reuse local workflow from other repository GitHub Actions
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      ZIG_BIN:
        description: "zig bin directory"
        value: ${{ jobs.zig.outputs.ZIG_BIN }}
jobs:
  zig:
    name: zig
    runs-on: ubuntu-latest
    # declare zig job outputs
    outputs:
      ZIG_BIN: ${{ steps.bin.outputs.ZIG_BIN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        id: zig-cache
        with:
          path: |
            ~/.zig
            ~/.local
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml') }}
      - run: |
          PATH="$HOME/.zig:$PATH" command -v zig >/dev/null 2>&1 || {
            echo >&2 "Zig is required but not installed."                                   ;
            #sudo apt install curl tar xz-utils -yqq                                        ;
            curl -fsSL https://ziglang.org/builds/zig-linux-x86_64-0.11.0.tar.xz | tar -xJv ;
            mv -fv zig-linux-x86_64-0.11.0 ${HOME}/.zig                                     ;
            mkdir -p ~/.local/bin ; ln -sv ~/.zig/zig ~/.local/bin/zig                      ;
            export ZIG_VERSION=`${HOME}/.zig/zig version`                                   ;
            echo "Installed ${ZIG_VERSION} version of zig."                                 ;
          }
      # set zig job outputs
      - id: bin
        run: echo "ZIG_BIN=${HOME}/.zig" >> $GITHUB_OUTPUT
#Usage:
#name: ...
#on: [...]
#jobs:
#  zig:
#    uses: ./.github/workflows/zig.yml  # <--- (1) zig uses job is required
#  job1:
#    runs-on: ubuntu-latest
#    needs: zig                         # <--- (2) needs of job zig is required
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/cache@v4         # <--- (3) same cache config is required
#        with:
#          path: |
#            ~/.zig
#            ~/.local
#          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml') }}
#      - run: zig version
